# Theme: Black Atom — Clay ∷ Light
# Appearance: light
# Collection: Clay

# Status bar
set -g status-style fg=#5d553f,bg=#f8f2dc
set -g status-left-style fg=#e76b3e,bg=#f8f2dc
set -g status-right-style fg=#5d553f,bg=#f8f2dc

# Window status
set-window-option -g window-status-style fg=#5d553f
set-window-option -g window-status-current-style fg=#e76b3e,bold
set-window-option -g window-status-activity-style fg=#00a3e9,bold
set-window-option -g window-status-bell-style fg=#00a3e9,bold

# Pane borders
set -g pane-border-style fg=#5d553f
set -g pane-active-border-style fg=#e76b3e

# Pane foreground (inactive panes dimmed)
set -g window-style fg=#5d553f
set -g window-active-style fg=#322e22

# Pane status bar
set -g pane-border-format "#{?pane_active,#[fg=#e76b3e]●,#[fg=#5d553f]○}"

# Session switcher & copy mode
set -g mode-style fg=#e76b3e,bg=#fff9e2

# Messages & command prompt - minimal style
set -g message-style fg=#00a3e9,bg=#f8f2dc,bold
set -g message-command-style fg=#e76b3e,bg=#f8f2dc

# Display panes
set -g display-panes-active-colour "#e76b3e"
set -g display-panes-colour "#5d553f"
