background = #f8f9f9
foreground = #2b3b33

selection-background = #e3e8e6
selection-foreground = #2b3b33

# Black
palette = 0=#425953
# Dark Red
palette = 1=#f472a0
# Dark Green
palette = 2=#53aa53
# Dark Yellow
palette = 3=#66bd10
# Dark Blue
palette = 4=#51796d
# Dark Magenta
palette = 5=#887bd3
# Dark Cyan
palette = 6=#3fa569
# Light Gray
palette = 7=#e3e8e6

# Gray
palette = 8=#51796d
# Red
palette = 9=#f472a0
# Green
palette = 10=#53aa53
# Yellow
palette = 11=#66bd10
# Blue
palette = 12=#51796d
# Magenta
palette = 13=#998ed9
# Cyan
palette = 14=#40bf75
# White
palette = 15=#f8f9f9
