background = #20252a
foreground = #e5ecf3

selection-background = #3e4349
selection-foreground = #e5ecf3

# Black
palette = 0=#3e4349
# Dark Red
palette = 1=#e97292
# Dark Green
palette = 2=#4cb86a
# Dark Yellow
palette = 3=#dd881b
# Dark Blue
palette = 4=#00b9c3
# Dark Magenta
palette = 5=#fb82a1
# Dark Cyan
palette = 6=#5bb661
# Light Gray
palette = 7=#dbe2e9

# Gray
palette = 8=#6a6f76
# Red
palette = 9=#e97292
# Green
palette = 10=#4cb86a
# Yellow
palette = 11=#dd881b
# Blue
palette = 12=#00b9c3
# Magenta
palette = 13=#7faaff
# Cyan
palette = 14=#4ec983
# White
palette = 15=#e5ecf3
