background = #d8dfe6
foreground = #0e1217

selection-background = #a8afb5
selection-foreground = #0e1217

# Black
palette = 0=#0e1217
# Dark Red
palette = 1=#ff50a7
# Dark Green
palette = 2=#00a800
# Dark Yellow
palette = 3=#ff7e00
# Dark Blue
palette = 4=#00abc1
# Dark Magenta
palette = 5=#df6989
# Dark Cyan
palette = 6=#409d48
# Light Gray
palette = 7=#757b81

# Gray
palette = 8=#43484e
# Red
palette = 9=#ff50a7
# Green
palette = 10=#00a800
# Yellow
palette = 11=#ff7e00
# Blue
palette = 12=#00abc1
# Magenta
palette = 13=#6791f1
# Cyan
palette = 14=#2eaf6b
# White
palette = 15=#a8afb5
