background = #f8f2dc
foreground = #322e22

selection-background = #ddd8c2
selection-foreground = #322e22

# Black
palette = 0=#4c473c
# Dark Red
palette = 1=#f14d4c
# Dark Green
palette = 2=#819e00
# Dark Yellow
palette = 3=#cd7b00
# Dark Blue
palette = 4=#00a3e9
# Dark Magenta
palette = 5=#79715a
# Dark Cyan
palette = 6=#888069
# Light Gray
palette = 7=#888069

# Gray
palette = 8=#5d553f
# Red
palette = 9=#f14d4c
# Green
palette = 10=#819e00
# Yellow
palette = 11=#cd7b00
# Blue
palette = 12=#00a3e9
# Magenta
palette = 13=#79715a
# Cyan
palette = 14=#888069
# White
palette = 15=#888069
