background = #302e28
foreground = #e3decc

selection-background = #4a4842
selection-foreground = #e3decc

# Black
palette = 0=#4a4842
# Dark Red
palette = 1=#dd7577
# Dark Green
palette = 2=#a9ba78
# Dark Yellow
palette = 3=#d6b174
# Dark Blue
palette = 4=#79b5cc
# Dark Magenta
palette = 5=#a49e8d
# Dark Cyan
palette = 6=#b4ae9c
# Light Gray
palette = 7=#b4ae9c

# Gray
palette = 8=#777161
# Red
palette = 9=#dd7577
# Green
palette = 10=#a9ba78
# Yellow
palette = 11=#d6b174
# Blue
palette = 12=#79b5cc
# Magenta
palette = 13=#a49e8d
# Cyan
palette = 14=#b4ae9c
# White
palette = 15=#b4ae9c
