# Theme: Black Atom — TERRA ∷ Summer Dark
# Appearance: dark
# Collection: Terra

# Status bar
set -g status-style fg=#94a585,bg=#001b1a
set -g status-left-style fg=#bcb067,bg=#001b1a
set -g status-right-style fg=#94a585,bg=#001b1a

# Window status
set-window-option -g window-status-style fg=#94a585
set-window-option -g window-status-current-style fg=#bcb067,bold
set-window-option -g window-status-activity-style fg=#89a88e,bold
set-window-option -g window-status-bell-style fg=#89a88e,bold

# Pane borders
set -g pane-border-style fg=#94a585
set -g pane-active-border-style fg=#bcb067

# Pane foreground (inactive panes dimmed)
set -g window-style fg=#94a585
set -g window-active-style fg=#dfcbaa

# Pane status bar
set -g pane-border-format "#{?pane_active,#[fg=#bcb067]●,#[fg=#94a585]○}"

# Session switcher & copy mode
set -g mode-style fg=#bcb067,bg=#092520

# Messages & command prompt - minimal style
set -g message-style fg=#89a88e,bg=#001b1a,bold
set -g message-command-style fg=#bcb067,bg=#001b1a

# Display panes
set -g display-panes-active-colour "#bcb067"
set -g display-panes-colour "#94a585"
