[metadata]
author = "Black Atom Industries"
name = "Black Atom — Minium ∷ Viridian Dark"

[colors]
foreground = "#dcf1e9"
background = "#194034"
cursor_bg = "#ed9562"
cursor_border = "#ed9562"
cursor_fg = "#194034"
selection_bg = "#215848"
selection_fg = "#dcf1e9"
split = "#ed9562"
compose_cursor = "#dd7577"
scrollbar_thumb = "#6fb59d"

ansi = [
  "#215848", # black
  "#88cfb6", # dark_red
  "#6fc483", # dark_green
  "#e09f4d", # dark_yellow
  "#88cfb6", # dark_blue
  "#cba1aa", # dark_magenta
  "#47c7a2", # dark_cyan
  "#88cfb6" # light_gray
]

brights = [
  "#3a816a", # gray
  "#88cfb6", # red
  "#6fc483", # green
  "#e09f4d", # yellow
  "#88cfb6", # blue
  "#ecc1c9", # magenta
  "#47c7a2", # cyan
  "#88cfb6" # white
]

[colors.tab_bar]
inactive_tab_edge = "#12352a"
background = "#194034"

[colors.tab_bar.active_tab]
fg_color = "#194034"
bg_color = "#ed9562"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#194034"
bg_color = "#215848"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#194034"
bg_color = "#204c3e"

[colors.tab_bar.new_tab]
fg_color = "#194034"
bg_color = "#a9ba78"

[colors.tab_bar.new_tab_hover]
fg_color = "#194034"
bg_color = "#204c3e"
intensity = "Bold"
