[metadata]
author = "Black Atom Industries"
name = "Black Atom — Minium ∷ Polymer Dark"

[colors]
foreground = "#f2fafd"
background = "#030608"
cursor_bg = "#fc8e06"
cursor_border = "#fc8e06"
cursor_fg = "#030608"
selection_bg = "#111719"
selection_fg = "#f2fafd"
split = "#fc8e06"
compose_cursor = "#dd7577"
scrollbar_thumb = "#868e90"

ansi = [
  "#111719", # black
  "#9ea6a9", # dark_red
  "#868e90", # dark_green
  "#1a97fc", # dark_yellow
  "#9ea6a9", # dark_blue
  "#868e90", # dark_magenta
  "#9ea6a9", # dark_cyan
  "#9ea6a9" # light_gray
]

brights = [
  "#585f61", # gray
  "#9ea6a9", # red
  "#868e90", # green
  "#fc8e06", # yellow
  "#9ea6a9", # blue
  "#868e90", # magenta
  "#9ea6a9", # cyan
  "#9ea6a9" # white
]

[colors.tab_bar]
inactive_tab_edge = "#000203"
background = "#030608"

[colors.tab_bar.active_tab]
fg_color = "#030608"
bg_color = "#fc8e06"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#030608"
bg_color = "#111719"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#030608"
bg_color = "#090e10"

[colors.tab_bar.new_tab]
fg_color = "#030608"
bg_color = "#a9ba78"

[colors.tab_bar.new_tab_hover]
fg_color = "#030608"
bg_color = "#090e10"
intensity = "Bold"
