background = #261a2a
foreground = #ead2b2

selection-background = #4a3d50
selection-foreground = #ead2b2

# Black
palette = 0=#4a3d50
# Dark Red
palette = 1=#fe838f
# Dark Green
palette = 2=#7fc08c
# Dark Yellow
palette = 3=#e49e22
# Dark Blue
palette = 4=#b5a4d7
# Dark Magenta
palette = 5=#c07d55
# Dark Cyan
palette = 6=#38a391
# Light Gray
palette = 7=#b19b7c

# Gray
palette = 8=#756c89
# Red
palette = 9=#fe838f
# Green
palette = 10=#7fc08c
# Yellow
palette = 11=#e49e22
# Blue
palette = 12=#b5a4d7
# Magenta
palette = 13=#e19b73
# Cyan
palette = 14=#5cc3b0
# White
palette = 15=#d1ba9b
