background = #351b23
foreground = #d4bfd6

selection-background = #5b3e47
selection-foreground = #d4bfd6

# Black
palette = 0=#5b3e47
# Dark Red
palette = 1=#ff857b
# Dark Green
palette = 2=#80bda2
# Dark Yellow
palette = 3=#dca23a
# Dark Blue
palette = 4=#8cb6c5
# Dark Magenta
palette = 5=#b9a2d4
# Dark Cyan
palette = 6=#62adac
# Light Gray
palette = 7=#946996

# Gray
palette = 8=#7d5178
# Red
palette = 9=#ff857b
# Green
palette = 10=#80bda2
# Yellow
palette = 11=#dca23a
# Blue
palette = 12=#8cb6c5
# Magenta
palette = 13=#d49bb2
# Cyan
palette = 14=#72bdbc
# White
palette = 15=#b796b8
