background = #fef2e1
foreground = #3a2e3b

selection-background = #f8e7d0
selection-foreground = #3a2e3b

# Black
palette = 0=#634c64
# Dark Red
palette = 1=#f5345e
# Dark Green
palette = 2=#3aa85b
# Dark Yellow
palette = 3=#ed9a00
# Dark Blue
palette = 4=#9e77dc
# Dark Magenta
palette = 5=#f2943c
# Dark Cyan
palette = 6=#008c75
# Light Gray
palette = 7=#d1ba9b

# Gray
palette = 8=#725a73
# Red
palette = 9=#f5345e
# Green
palette = 10=#3aa85b
# Yellow
palette = 11=#ed9a00
# Blue
palette = 12=#9e77dc
# Magenta
palette = 13=#f88f4f
# Cyan
palette = 14=#00ab93
# White
palette = 15=#f2daba
