background = #1c1c1c
foreground = #e6e6e6

selection-background = #373737
selection-foreground = #e6e6e6

# Black
palette = 0=#373737
# Dark Red
palette = 1=#f591b2
# Dark Green
palette = 2=#90b99f
# Dark Yellow
palette = 3=#eab899
# Dark Blue
palette = 4=#a1b0cf
# Dark Magenta
palette = 5=#9789c3
# Dark Cyan
palette = 6=#76bdac
# Light Gray
palette = 7=#9d9daf

# Gray
palette = 8=#69697f
# Red
palette = 9=#f591b2
# Green
palette = 10=#90b99f
# Yellow
palette = 11=#eab899
# Blue
palette = 12=#a1b0cf
# Magenta
palette = 13=#aca1cf
# Cyan
palette = 14=#8dd9c5
# White
palette = 15=#b3b3b3
