background = #1d364f
foreground = #e2ebf3

selection-background = #2a435d
selection-foreground = #e2ebf3

# Black
palette = 0=#2a435d
# Dark Red
palette = 1=#dd7577
# Dark Green
palette = 2=#a9ba78
# Dark Yellow
palette = 3=#d6b174
# Dark Blue
palette = 4=#79b5cc
# Dark Magenta
palette = 5=#6c93bc
# Dark Cyan
palette = 6=#8ab2dc
# Light Gray
palette = 7=#8ab2dc

# Gray
palette = 8=#4f759c
# Red
palette = 9=#dd7577
# Green
palette = 10=#a9ba78
# Yellow
palette = 11=#d6b174
# Blue
palette = 12=#79b5cc
# Magenta
palette = 13=#6c93bc
# Cyan
palette = 14=#8ab2dc
# White
palette = 15=#8ab2dc
