local theme = {
    meta = {
        key = "black-atom-mnml-47-light",
        label = "Black Atom — MNML ∷ 47 Light",
        appearance = "light",
        status = "development",
        collection = {
            key = "mnml",
            label = "MNML",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#12352a",
            d20 = "#194034",
            d30 = "#204c3e",
            d40 = "#215848",
            m10 = "#3a816a",
            m20 = "#569c85",
            m30 = "#6fb59d",
            m40 = "#88cfb6",
            l10 = "#aed5c6",
            l20 = "#c2dfd4",
            l30 = "#dcf1e9",
            l40 = "#f1fbf7",
        },
        palette = {
            black = "#215848",
            gray = "#3a816a",
            dark_red = "#88cfb6",
            red = "#88cfb6",
            dark_green = "#00af44",
            green = "#00af44",
            dark_yellow = "#e95e00",
            yellow = "#e95e00",
            dark_blue = "#88cfb6",
            blue = "#88cfb6",
            dark_magenta = "#ab838b",
            magenta = "#bb929a",
            dark_cyan = "#00b37c",
            cyan = "#00b37c",
            light_gray = "#88cfb6",
            white = "#88cfb6",
        },
        ui = {
            bg = {
                default = "#dcf1e9",
                panel = "#c2dfd4",
                float = "#c2dfd4",
                active = "#f1fbf7",
                disabled = "#aed5c6",
                hover = "#c2dfd4",
                selection = "#aed5c6",
                search = "#aed5c6",
                contrast = "#215848",
                negative = "#fdd1cc",
                warn = "#efd9c5",
                info = "#c9e4f6",
                hint = "#efd9c5",
                positive = "#d9e2c5",
                add = "#d9e2c5",
                delete = "#fdd1cc",
                modify = "#c9e4f6",
            },
            fg = {
                default = "#194034",
                subtle = "#3a816a",
                accent = "#e95e00",
                disabled = "#6fb59d",
                contrast = "#c2dfd4",
                negative = "#f14d4c",
                warn = "#cd7b00",
                info = "#00a3e9",
                hint = "#cd7b00",
                positive = "#819e00",
                add = "#819e00",
                delete = "#f14d4c",
                modify = "#00a3e9",
            },
        },
        syntax = {
            variable = {
                default = "#204c3e",
                builtin = "#215848",
                member = "#00af44",
                parameter = "#00af44",
            },
            property = {
                default = "#3a816a",
            },
            string = {
                default = "#569c85",
                doc = "#00af44",
                regexp = "#e95e00",
                escape = "#e95e00",
            },
            constant = {
                default = "#194034",
                builtin = "#12352a",
            },
            module = {
                default = "#204c3e",
            },
            boolean = {
                default = "#3a816a",
            },
            number = {
                default = "#215848",
            },
            type = {
                default = "#12352a",
                builtin = "#215848",
            },
            attribute = {
                default = "#00af44",
                builtin = "#00af44",
            },
            func = {
                default = "#e95e00",
                builtin = "#00af44",
                method = "#00af44",
            },
            constructor = {
                default = "#e95e00",
            },
            keyword = {
                default = "#e95e00",
                import = "#00af44",
                export = "#d97100",
            },
            operator = {
                default = "#194034",
            },
            punctuation = {
                default = "#215848",
                delimiter = "#215848",
                bracket = "#215848",
                special = "#215848",
            },
            comment = {
                default = "#569c85",
                doc = "#569c85",
                todo = "#819e00",
                error = "#f14d4c",
                warn = "#cd7b00",
                info = "#00a3e9",
                hint = "#00a3e9",
            },
            markup = {
                heading = {
                    h1 = "#e95e00",
                    h2 = "#e95e00",
                    h3 = "#e95e00",
                    h4 = "#3a816a",
                    h5 = "#3a816a",
                    h6 = "#3a816a",
                },
                strong = "#e95e00",
                italic = "#e95e00",
                strikethrough = "#e95e00",
                quote = "#6fb59d",
                math = "#569c85",
                link = "#00af44",
                list = {
                    default = "#3a816a",
                    checked = "#819e00",
                    unchecked = "#3a816a",
                },
                code = {
                    fg = "#215848",
                    bg = "#c2dfd4",
                },
            },
            tag = {
                default = "#00af44",
                builtin = "#e95e00",
                attribute = "#3a816a",
                delimiter = "#6fb59d",
            },
        },
    },
}

require("black-atom").load(theme)
