local theme = {
    meta = {
        key = "black-atom-minium-viridian-dark",
        label = "Black Atom — Minium ∷ Viridian Dark",
        appearance = "dark",
        status = "development",
        collection = {
            key = "minium",
            label = "Minium",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#12352a",
            d20 = "#194034",
            d30 = "#204c3e",
            d40 = "#215848",
            m10 = "#3a816a",
            m20 = "#569c85",
            m30 = "#6fb59d",
            m40 = "#88cfb6",
            l10 = "#aed5c6",
            l20 = "#c2dfd4",
            l30 = "#dcf1e9",
            l40 = "#f1fbf7",
        },
        palette = {
            black = "#215848",
            gray = "#3a816a",
            dark_red = "#88cfb6",
            red = "#88cfb6",
            dark_green = "#6fc483",
            green = "#6fc483",
            dark_yellow = "#e09f4d",
            yellow = "#e09f4d",
            dark_blue = "#88cfb6",
            blue = "#88cfb6",
            dark_magenta = "#cba1aa",
            magenta = "#ecc1c9",
            dark_cyan = "#47c7a2",
            cyan = "#47c7a2",
            light_gray = "#88cfb6",
            white = "#88cfb6",
        },
        ui = {
            bg = {
                default = "#194034",
                panel = "#12352a",
                float = "#12352a",
                active = "#204c3e",
                disabled = "#215848",
                hover = "#204c3e",
                selection = "#215848",
                search = "#215848",
                contrast = "#aed5c6",
                negative = "#704a4a",
                warn = "#6c5f4a",
                info = "#4c6069",
                hint = "#6c5f4a",
                positive = "#5c624b",
                add = "#5c624b",
                delete = "#704a4a",
                modify = "#4c6069",
            },
            fg = {
                default = "#dcf1e9",
                subtle = "#6fb59d",
                accent = "#ed9562",
                disabled = "#569c85",
                contrast = "#194034",
                negative = "#dd7577",
                warn = "#d6b174",
                info = "#79b5cc",
                hint = "#d6b174",
                positive = "#a9ba78",
                add = "#a9ba78",
                delete = "#dd7577",
                modify = "#79b5cc",
            },
        },
        syntax = {
            variable = {
                default = "#c2dfd4",
                builtin = "#aed5c6",
                member = "#6fc483",
                parameter = "#e09f4d",
            },
            property = {
                default = "#6fc483",
            },
            string = {
                default = "#c2dfd4",
                doc = "#aed5c6",
                regexp = "#f1fbf7",
                escape = "#f1fbf7",
            },
            constant = {
                default = "#aed5c6",
                builtin = "#c2dfd4",
            },
            module = {
                default = "#c2dfd4",
            },
            boolean = {
                default = "#88cfb6",
            },
            number = {
                default = "#aed5c6",
            },
            type = {
                default = "#f1fbf7",
                builtin = "#f1fbf7",
            },
            attribute = {
                default = "#6fc483",
                builtin = "#6fc483",
            },
            func = {
                default = "#ed9562",
                builtin = "#6fc483",
                method = "#6fc483",
            },
            constructor = {
                default = "#ed9562",
            },
            keyword = {
                default = "#dcf1e9",
                import = "#f1fbf7",
                export = "#f1fbf7",
            },
            operator = {
                default = "#dcf1e9",
            },
            punctuation = {
                default = "#aed5c6",
                delimiter = "#aed5c6",
                bracket = "#aed5c6",
                special = "#aed5c6",
            },
            comment = {
                default = "#6fb59d",
                doc = "#6fb59d",
                todo = "#a9ba78",
                error = "#dd7577",
                warn = "#d6b174",
                info = "#79b5cc",
                hint = "#79b5cc",
            },
            markup = {
                heading = {
                    h1 = "#ed9562",
                    h2 = "#ed9562",
                    h3 = "#ed9562",
                    h4 = "#88cfb6",
                    h5 = "#88cfb6",
                    h6 = "#88cfb6",
                },
                strong = "#ed9562",
                italic = "#ed9562",
                strikethrough = "#ed9562",
                quote = "#569c85",
                math = "#569c85",
                link = "#6fc483",
                list = {
                    default = "#88cfb6",
                    checked = "#a9ba78",
                    unchecked = "#88cfb6",
                },
                code = {
                    fg = "#aed5c6",
                    bg = "#12352a",
                },
            },
            tag = {
                default = "#ed9562",
                builtin = "#6fc483",
                attribute = "#6fb59d",
                delimiter = "#aed5c6",
            },
        },
    },
}

require("black-atom").load(theme)
