# Theme: Black Atom — Facility ∷ Dimmed Dark
# Appearance: dark
# Collection: Facility

# Status bar
set -g status-style fg=#91bcad,bg=#21302d
set -g status-left-style fg=#b7db6e,bg=#21302d
set -g status-right-style fg=#91bcad,bg=#21302d

# Window status
set-window-option -g window-status-style fg=#91bcad
set-window-option -g window-status-current-style fg=#b7db6e,bold
set-window-option -g window-status-activity-style fg=#abe7ca,bold
set-window-option -g window-status-bell-style fg=#abe7ca,bold

# Pane borders
set -g pane-border-style fg=#91bcad
set -g pane-active-border-style fg=#b7db6e

# Pane foreground (inactive panes dimmed)
set -g window-style fg=#91bcad
set -g window-active-style fg=#c1efd5

# Pane status bar
set -g pane-border-format "#{?pane_active,#[fg=#b7db6e]●,#[fg=#91bcad]○}"

# Session switcher & copy mode
set -g mode-style fg=#b7db6e,bg=#293c36

# Messages & command prompt - minimal style
set -g message-style fg=#abe7ca,bg=#21302d,bold
set -g message-command-style fg=#b7db6e,bg=#21302d

# Display panes
set -g display-panes-active-colour "#b7db6e"
set -g display-panes-colour "#91bcad"
