background = #030608
foreground = #f2fafd

selection-background = #111719
selection-foreground = #f2fafd

# Black
palette = 0=#111719
# Dark Red
palette = 1=#dd7577
# Dark Green
palette = 2=#a9ba78
# Dark Yellow
palette = 3=#d6b174
# Dark Blue
palette = 4=#79b5cc
# Dark Magenta
palette = 5=#868e90
# Dark Cyan
palette = 6=#9ea6a9
# Light Gray
palette = 7=#9ea6a9

# Gray
palette = 8=#585f61
# Red
palette = 9=#dd7577
# Green
palette = 10=#a9ba78
# Yellow
palette = 11=#d6b174
# Blue
palette = 12=#79b5cc
# Magenta
palette = 13=#868e90
# Cyan
palette = 14=#9ea6a9
# White
palette = 15=#9ea6a9
