background = #194034
foreground = #dcf1e9

selection-background = #215848
selection-foreground = #dcf1e9

# Black
palette = 0=#215848
# Dark Red
palette = 1=#dd7577
# Dark Green
palette = 2=#a9ba78
# Dark Yellow
palette = 3=#d6b174
# Dark Blue
palette = 4=#79b5cc
# Dark Magenta
palette = 5=#cba1aa
# Dark Cyan
palette = 6=#47c7a2
# Light Gray
palette = 7=#88cfb6

# Gray
palette = 8=#3a816a
# Red
palette = 9=#dd7577
# Green
palette = 10=#a9ba78
# Yellow
palette = 11=#d6b174
# Blue
palette = 12=#79b5cc
# Magenta
palette = 13=#ecc1c9
# Cyan
palette = 14=#47c7a2
# White
palette = 15=#88cfb6
