
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getConfig() : Promise<Config> {
    return await TAURI_INVOKE("get_config");
},
async saveConfig(config: Config) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Per-adapter setup state: provisioning class, the config fields its
 * updater reads, and whether its Linked placement is wired on disk.
 */
async getAppStatus() : Promise<Result<AppStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Wire an adapter's own themes location to the unpacked theme files via
 * symlinks (create, heal, prune). Explicit adapter-setup action. The
 * target dir is derived from each adapter's configured location (its
 * sibling `themes/`; for Obsidian, each configured config_folder gets
 * `<config_folder>/.obsidian/themes/`), so custom setups link into the right place.
 */
async linkAppThemes(app: AppName) : Promise<LinkThemesResult> {
    return await TAURI_INVOKE("link_app_themes", { app });
},
/**
 * Conservative app detection: an app counts as found iff its configured
 * location exists on disk. Obsidian checks its configured config folders; other
 * adapters check their configured config file. No binary lookups or
 * alternative-path guessing.
 */
async detectApps() : Promise<AppDetection[]> {
    return await TAURI_INVOKE("detect_apps");
},
/**
 * Single entry point for all app updates. The frontend calls this once per app.
 * 
 * Each invocation reads config from disk independently — this is inherent to the
 * Tauri IPC model where each `invoke` call is a separate request. At the current
 * scale (~5 apps, tiny JSON file) this is fine.
 */
async updateApp(app: AppName, theme: ThemeContext) : Promise<UpdateResult> {
    return await TAURI_INVOKE("update_app", { app, theme });
},
/**
 * Toggle system-wide dark/light mode. Separate from update_app because system
 * appearance is not an app with AppConfig — it's a standalone boolean toggle.
 */
async updateSystemAppearance(appearance: string) : Promise<UpdateResult> {
    return await TAURI_INVOKE("update_system_appearance", { appearance });
},
/**
 * Check one adapter's configured location: does it exist, and does its
 * match_pattern hit? Read-only, never writes.
 */
async verifyAppPath(app: AppName) : Promise<AppPathVerification> {
    return await TAURI_INVOKE("verify_app_path", { app });
},
/**
 * Save the Neovim plugin settings and write them into the managed Lua
 * block in nvim's SETTINGS_PATH. The file must already exist — Livery
 * patches a Neovim entry point, it does not create one.
 */
async writeNvimSettings(settings: NvimSettings) : Promise<UpdateResult> {
    return await TAURI_INVOKE("write_nvim_settings", { settings });
},
/**
 * The theme livery last applied, as a theme key. `None` on a machine that
 * has never run setup.
 */
async getActiveTheme() : Promise<string | null> {
    return await TAURI_INVOKE("get_active_theme");
},
/**
 * Record the theme livery just applied in the tracked livery config.
 */
async setActiveTheme(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_theme", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * A config field an adapter's updater actually reads. Drives which inputs
 * the settings UI offers per adapter — editing a field the updater ignores
 * is silent noise; editing one it does read, wrongly, breaks switching.
 */
export type AdapterEditableField = "config_path" | "themes_path" | "match_pattern" | "replace_template" | 
/**
 * nvim only: the file the managed Lua settings block is written into.
 */
"settings_path"
export type AppConfig = { enabled?: boolean; 
/**
 * Generic adapter config file. Obsidian leaves this empty and stores
 * configuration folders instead.
 */
config_path?: string | null; 
/**
 * Obsidian configuration folders, such as `~/Notes/.obsidian`.
 */
config_folders?: string[] | null; themes_path?: string | null; match_pattern?: string | null; replace_template?: string | null; 
/**
 * nvim only: the file the managed Lua block is written into.
 */
settings_path?: string | null; 
/**
 * nvim only: the plugin options the managed Lua block renders.
 */
settings?: NvimSettings | null }
/**
 * One adapter's detection outcome — backs the settings AUTO-DETECT action.
 */
export type AppDetection = { app: AppName; 
/**
 * The expanded path that was checked (empty = nothing to check).
 */
config_path: string; 
/**
 * Obsidian configuration folders discovered from its global registry.
 */
config_folders?: string[] | null; found: boolean }
/**
 * Supported app names. TypeScript bindings are auto-generated via tauri-specta.
 */
export type AppName = "nvim" | "tmux" | "ghostty" | "zed" | "delta" | "lazygit" | "herdr" | "obsidian" | "helm-tmux"
/**
 * Result of `verify_app_path` — backs the settings screen's [ VERIFY PATH ].
 */
export type AppPathVerification = { app: string; exists: boolean; config_folders?: ConfigFolderPathVerification[] | null; 
/**
 * `Some(hit)` when the adapter has a match_pattern to check; `None` for
 * structural patchers (YAML/JSONC merge) where existence is the whole check.
 */
pattern_matches: boolean | null; 
/**
 * Why verification itself could not run (bad regex, unreadable file).
 */
message?: string | null }
/**
 * One adapter's setup state: which class it belongs to, which config fields
 * its updater reads, and whether its Linked placement is wired on disk.
 */
export type AppStatus = { app: AppName; 
/**
 * Who consumes the managed theme files — drives the class-specific
 * settings row content and the SET UP chain.
 */
provisioning: ThemeProvisioning; 
/**
 * Config fields this adapter's updater actually reads — trims the
 * settings field grid to what's safe to edit.
 */
editable_fields: AdapterEditableField[]; 
/**
 * The adapter's placement resolves to the managed themes dir right now.
 * Always `false` for External and Merged adapters, which have no
 * placement to wire.
 */
linked: boolean }
export type Config = { 
/**
 * Versioned configuration schema. Missing on disk means legacy v1.
 */
version?: number; system_appearance: boolean; active_theme?: string | null; keymappings?: Keymappings; apps: { [key in AppName]: AppConfig } }
export type ConfigFolderLinkOutcome = { config_folder: string; status: UpdateStatus; message?: string | null; linked: number; pruned: number }
export type ConfigFolderOutcome = { config_folder: string; status: UpdateStatus; message?: string | null; reload_warning?: string | null }
export type ConfigFolderPathVerification = { 
/**
 * The configured identity used by the settings UI to associate the result.
 */
config_folder: string; 
/**
 * The expanded filesystem path that was checked.
 */
path: string; exists: boolean }
export type Keymappings = { toggle_window: string }
/**
 * Outcome of wiring one adapter's themes dir via managed symlinks.
 */
export type LinkThemesResult = { app: string; status: UpdateStatus; config_folders?: ConfigFolderLinkOutcome[] | null; message?: string | null; linked: number | null; pruned: number | null }
export type NvimDiagnostics = { undercurl: boolean; background: boolean }
/**
 * The plugin's `vim.g.black_atom_core_config` table, one field per option
 * `adapters/nvim/lua/black-atom/config.lua` declares. The shape is the
 * contract: it is rendered back into Lua verbatim, so a renamed field here
 * silently stops reaching the plugin.
 */
export type NvimSettings = { term_colors: boolean; styles: NvimStyles }
/**
 * Bold/italic pair for one syntax group. Mirrors
 * `BlackAtom.HighlightDefinition` as far as the settings page exposes it.
 */
export type NvimStyle = { bold: boolean; italic: boolean }
export type NvimStyles = { 
/**
 * `"none"`, `"partial"`, or `"full"`.
 */
transparency: string; ending_tildes: boolean; 
/**
 * `"fg"` or `"bg"`.
 */
cmp_kind_color_mode: string; dark_sidebars: boolean; dark_floats: boolean; diagnostics: NvimDiagnostics; syntax: NvimSyntax }
/**
 * Per-group syntax styling. One entry per group the plugin reads.
 */
export type NvimSyntax = { comments: NvimStyle; keywords: NvimStyle; functions: NvimStyle; strings: NvimStyle; variables: NvimStyle; messages: NvimStyle }
/**
 * Theme metadata passed from the frontend.
 */
export type ThemeContext = { theme_key: string; appearance: string; collection_key: string; theme_label: string | null }
/**
 * Theme provisioning — who consumes the managed theme files (see ADAPTERS.md).
 * 
 * - `External`: the app's theme files are provided outside of livery (plugin,
 * compiled binary, or the user), so livery only performs switching.
 * - `Linked`: livery symlinks the unpacked theme files into a location the app
 * itself reads; switching selects one via a pointer in the app's config.
 * - `Merged`: the app cannot read external theme files, so on every switch
 * livery reads the unpacked theme file and writes its values into the config.
 */
export type ThemeProvisioning = "external" | "linked" | "merged"
export type UpdateResult = { app: string; status: UpdateStatus; message?: string | null; 
/**
 * Per-configuration-folder outcomes for Obsidian's batch update.
 */
config_folders?: ConfigFolderOutcome[] | null; 
/**
 * Time taken by the updater in milliseconds.
 * Set by the dispatcher, not by individual updaters.
 */
duration_ms: number | null }
export type UpdateStatus = "done" | "error" | "skipped"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
