background = #12161d
foreground = #e2e8f2

selection-background = #212f3f
selection-foreground = #e2e8f2

# Black
palette = 0=#212f3f
# Dark Red
palette = 1=#a8a6e5
# Dark Green
palette = 2=#82c3d3
# Dark Yellow
palette = 3=#fba952
# Dark Blue
palette = 4=#7fb6ee
# Dark Magenta
palette = 5=#9f8fbe
# Dark Cyan
palette = 6=#64b3c0
# Light Gray
palette = 7=#c0ccdb

# Gray
palette = 8=#3f556b
# Red
palette = 9=#a8a6e5
# Green
palette = 10=#82c3d3
# Yellow
palette = 11=#fba952
# Blue
palette = 12=#7fb6ee
# Magenta
palette = 13=#b4a7df
# Cyan
palette = 14=#71cfd9
# White
palette = 15=#e2e8f2
