background = #f7e9d6
foreground = #00280f

selection-background = #ffeedd
selection-foreground = #00280f

# Black
palette = 0=#245427
# Dark Red
palette = 1=#ac6e59
# Dark Green
palette = 2=#768c00
# Dark Yellow
palette = 3=#c67b36
# Dark Blue
palette = 4=#5a8f65
# Dark Magenta
palette = 5=#aa7fa5
# Dark Cyan
palette = 6=#1c7360
# Light Gray
palette = 7=#a2a457

# Gray
palette = 8=#26541c
# Red
palette = 9=#ac6e59
# Green
palette = 10=#768c00
# Yellow
palette = 11=#c67b36
# Blue
palette = 12=#5a8f65
# Magenta
palette = 13=#b67c8d
# Cyan
palette = 14=#459178
# White
palette = 15=#f7e9d6
