background = #001b1a
foreground = #dfcbaa

selection-background = #2a433a
selection-foreground = #dfcbaa

# Black
palette = 0=#2a433a
# Dark Red
palette = 1=#c88f7b
# Dark Green
palette = 2=#96a85e
# Dark Yellow
palette = 3=#bcb067
# Dark Blue
palette = 4=#89a88e
# Dark Magenta
palette = 5=#92768f
# Dark Cyan
palette = 6=#4b8f7e
# Light Gray
palette = 7=#baad8a

# Gray
palette = 8=#2e503e
# Red
palette = 9=#c88f7b
# Green
palette = 10=#96a85e
# Yellow
palette = 11=#bcb067
# Blue
palette = 12=#89a88e
# Magenta
palette = 13=#ba929d
# Cyan
palette = 14=#6aae9c
# White
palette = 15=#dfcbaa
