background = #212523
foreground = #d6d0c2

selection-background = #313634
selection-foreground = #d6d0c2

# Black
palette = 0=#313634
# Dark Red
palette = 1=#ba6e5f
# Dark Green
palette = 2=#92d49a
# Dark Yellow
palette = 3=#d1a762
# Dark Blue
palette = 4=#99b9e6
# Dark Magenta
palette = 5=#d5a9c3
# Dark Cyan
palette = 6=#679980
# Light Gray
palette = 7=#b8aa94

# Gray
palette = 8=#394740
# Red
palette = 9=#ba6e5f
# Green
palette = 10=#92d49a
# Yellow
palette = 11=#d1a762
# Blue
palette = 12=#99b9e6
# Magenta
palette = 13=#c6b3da
# Cyan
palette = 14=#85ad9f
# White
palette = 15=#d6d0c2
