background = #241710
foreground = #eac5b1

selection-background = #382a23
selection-foreground = #eac5b1

# Black
palette = 0=#382a23
# Dark Red
palette = 1=#e87a69
# Dark Green
palette = 2=#95a483
# Dark Yellow
palette = 3=#d68c00
# Dark Blue
palette = 4=#d08c62
# Dark Magenta
palette = 5=#c67a65
# Dark Cyan
palette = 6=#719b8f
# Light Gray
palette = 7=#c9a592

# Gray
palette = 8=#86563b
# Red
palette = 9=#e87a69
# Green
palette = 10=#95a483
# Yellow
palette = 11=#d68c00
# Blue
palette = 12=#d08c62
# Magenta
palette = 13=#d4896e
# Cyan
palette = 14=#7ea99c
# White
palette = 15=#eac5b1
