[package]
name = "livery-cli"
version = "0.6.0"
description = "Black Atom livery command line interface"
authors = ["Black Atom Industries"]
license = "MIT"
repository = "https://github.com/nikbrunner/black-atom"
edition = "2021"
rust-version = "1.82"

[[bin]]
name = "livery"
path = "src/main.rs"

[dependencies]
livery_core = { path = "../core" }
clap = { version = "4", features = ["derive"] }
inquire = "0.7"
tokio = { version = "1", features = ["rt"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"
serde_json = "1.0"
