[metadata]
author = "Black Atom Industries"
name = "Black Atom — Dimmed Light"

[colors]
foreground = "#0e1217"
background = "#d8dfe6"
cursor_bg = "#2eaf6b"
cursor_border = "#2eaf6b"
cursor_fg = "#d8dfe6"
selection_bg = "#a8afb5"
selection_fg = "#0e1217"
split = "#2eaf6b"
compose_cursor = "#ff50a7"
scrollbar_thumb = "#43484e"

ansi = [
  "#0e1217", # black
  "#53595f", # dark_red
  "#757b81", # dark_green
  "#646a70", # dark_yellow
  "#53595f", # dark_blue
  "#df6989", # dark_magenta
  "#409d48", # dark_cyan
  "#757b81" # light_gray
]

brights = [
  "#43484e", # gray
  "#53595f", # red
  "#757b81", # green
  "#646a70", # yellow
  "#53595f", # blue
  "#6791f1", # magenta
  "#2eaf6b", # cyan
  "#a8afb5" # white
]

[colors.tab_bar]
inactive_tab_edge = "#c8ced5"
background = "#d8dfe6"

[colors.tab_bar.active_tab]
fg_color = "#c8ced5"
bg_color = "#2eaf6b"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#c8ced5"
bg_color = "#a8afb5"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c8ced5"
bg_color = "#a8afb5"

[colors.tab_bar.new_tab]
fg_color = "#c8ced5"
bg_color = "#00a800"

[colors.tab_bar.new_tab_hover]
fg_color = "#c8ced5"
bg_color = "#a8afb5"
intensity = "Bold"