[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNML ∷ 47 Light"

[colors]
foreground = "#194034"
background = "#dcf1e9"
cursor_bg = "#e95e00"
cursor_border = "#e95e00"
cursor_fg = "#dcf1e9"
selection_bg = "#aed5c6"
selection_fg = "#194034"
split = "#e95e00"
compose_cursor = "#f14d4c"
scrollbar_thumb = "#3a816a"

ansi = [
  "#215848", # black
  "#88cfb6", # dark_red
  "#00af44", # dark_green
  "#e95e00", # dark_yellow
  "#88cfb6", # dark_blue
  "#ab838b", # dark_magenta
  "#00b37c", # dark_cyan
  "#88cfb6" # light_gray
]

brights = [
  "#3a816a", # gray
  "#88cfb6", # red
  "#00af44", # green
  "#e95e00", # yellow
  "#88cfb6", # blue
  "#bb929a", # magenta
  "#00b37c", # cyan
  "#88cfb6" # white
]

[colors.tab_bar]
inactive_tab_edge = "#c2dfd4"
background = "#dcf1e9"

[colors.tab_bar.active_tab]
fg_color = "#c2dfd4"
bg_color = "#e95e00"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#c2dfd4"
bg_color = "#aed5c6"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c2dfd4"
bg_color = "#c2dfd4"

[colors.tab_bar.new_tab]
fg_color = "#c2dfd4"
bg_color = "#819e00"

[colors.tab_bar.new_tab_hover]
fg_color = "#c2dfd4"
bg_color = "#c2dfd4"
intensity = "Bold"