background = #dcf1e9
foreground = #194034

selection-background = #aed5c6
selection-foreground = #194034

# Black
palette = 0=#215848
# Dark Red
palette = 1=#f14d4c
# Dark Green
palette = 2=#819e00
# Dark Yellow
palette = 3=#cd7b00
# Dark Blue
palette = 4=#00a3e9
# Dark Magenta
palette = 5=#ab838b
# Dark Cyan
palette = 6=#00b37c
# Light Gray
palette = 7=#88cfb6

# Gray
palette = 8=#3a816a
# Red
palette = 9=#f14d4c
# Green
palette = 10=#819e00
# Yellow
palette = 11=#cd7b00
# Blue
palette = 12=#00a3e9
# Magenta
palette = 13=#bb929a
# Cyan
palette = 14=#00b37c
# White
palette = 15=#88cfb6
