name: "Black Atom :: Variants"
id: black-atom-variants
settings:
    - id: dark-theme-variant
      title: Dark Theme Variant
      description: Choose your Black Atom variant for dark mode
      type: class-select
      allowEmpty: false
      default: black-atom-default-dark
      options:
          - label: "Default: Dark"
            value: black-atom-default-dark
          - label: "Default: Dimmed Dark"
            value: black-atom-default-dimmed-dark
          - label: "Facility: Dark"
            value: black-atom-facility-dark
          - label: "Facility: Dimmed Dark"
            value: black-atom-facility-dimmed-dark
          - label: "TERRA: Spring Dark"
            value: black-atom-terra-spring-dark
          - label: "TERRA: Summer Dark"
            value: black-atom-terra-summer-dark
          - label: "TERRA: Fall Dark"
            value: black-atom-terra-fall-dark
          - label: "TERRA: Winter Dark"
            value: black-atom-terra-winter-dark
          - label: "JPN: Koyo Dark"
            value: black-atom-jpn-koyo-dark
          - label: "JPN: Murasaki Dark"
            value: black-atom-jpn-murasaki-dark
          - label: "JPN: Tsuki Dark"
            value: black-atom-jpn-tsuki-dark
          - label: "JPN: Sanshoku Dark"
            value: black-atom-jpn-sanshoku-dark
          - label: "Clay: Dark"
            value: black-atom-clay-dark
          - label: "Minium: Polymer Dark"
            value: black-atom-minium-polymer-dark
          - label: "Minium: Viridian Dark"
            value: black-atom-minium-viridian-dark
          - label: "Mono: Dark"
            value: black-atom-mono-dark
          - label: "Mono: Dimmed Dark"
            value: black-atom-mono-dimmed-dark
    - id: light-theme-variant
      title: Light Theme Variant
      description: Choose your Black Atom variant for light mode
      type: class-select
      allowEmpty: false
      default: black-atom-default-light
      options:
          - label: "Default: Light"
            value: black-atom-default-light
          - label: "Default: Dimmed Light"
            value: black-atom-default-dimmed-light
          - label: "Facility: Light"
            value: black-atom-facility-light
          - label: "Facility: Dimmed Light"
            value: black-atom-facility-dimmed-light
          - label: "TERRA: Spring Light"
            value: black-atom-terra-spring-light
          - label: "TERRA: Summer Light"
            value: black-atom-terra-summer-light
          - label: "TERRA: Fall Light"
            value: black-atom-terra-fall-light
          - label: "TERRA: Winter Light"
            value: black-atom-terra-winter-light
          - label: "JPN: Koyo Light"
            value: black-atom-jpn-koyo-light
          - label: "JPN: Sanshoku Light"
            value: black-atom-jpn-sanshoku-light
          - label: "Clay: Light"
            value: black-atom-clay-light
          - label: "Minium: Polymer Light"
            value: black-atom-minium-polymer-light
          - label: "Minium: Viridian Light"
            value: black-atom-minium-viridian-light
          - label: "Mono: Light"
            value: black-atom-mono-light
          - label: "Mono: Dimmed Light"
            value: black-atom-mono-dimmed-light
