background = #fefbf8
foreground = #181614

selection-background = #e0ddda
selection-foreground = #181614

# Black
palette = 0=#3f3d3a
# Dark Red
palette = 1=#f14d4c
# Dark Green
palette = 2=#819e00
# Dark Yellow
palette = 3=#cd7b00
# Dark Blue
palette = 4=#00a3e9
# Dark Magenta
palette = 5=#b3b0ae
# Dark Cyan
palette = 6=#c6c3c1
# Light Gray
palette = 7=#c6c3c1

# Gray
palette = 8=#8e8c89
# Red
palette = 9=#f14d4c
# Green
palette = 10=#819e00
# Yellow
palette = 11=#cd7b00
# Blue
palette = 12=#00a3e9
# Magenta
palette = 13=#b3b0ae
# Cyan
palette = 14=#c6c3c1
# White
palette = 15=#c6c3c1
