background = #0f0d0b
foreground = #edeae8

selection-background = #2b2826
selection-foreground = #edeae8

# Black
palette = 0=#2b2826
# Dark Red
palette = 1=#dd7577
# Dark Green
palette = 2=#a9ba78
# Dark Yellow
palette = 3=#d6b174
# Dark Blue
palette = 4=#79b5cc
# Dark Magenta
palette = 5=#82807d
# Dark Cyan
palette = 6=#a09e9b
# Light Gray
palette = 7=#a09e9b

# Gray
palette = 8=#4a4745
# Red
palette = 9=#dd7577
# Green
palette = 10=#a9ba78
# Yellow
palette = 11=#d6b174
# Blue
palette = 12=#79b5cc
# Magenta
palette = 13=#82807d
# Cyan
palette = 14=#a09e9b
# White
palette = 15=#a09e9b
