background = #dedede
foreground = #292929

selection-background = #c4c4c4
selection-foreground = #292929

# Black
palette = 0=#4d4d4d
# Dark Red
palette = 1=#f14d4c
# Dark Green
palette = 2=#819e00
# Dark Yellow
palette = 3=#cd7b00
# Dark Blue
palette = 4=#00a3e9
# Dark Magenta
palette = 5=#8c8c8c
# Dark Cyan
palette = 6=#a4a4a4
# Light Gray
palette = 7=#a4a4a4

# Gray
palette = 8=#5d5d5d
# Red
palette = 9=#f14d4c
# Green
palette = 10=#819e00
# Yellow
palette = 11=#cd7b00
# Blue
palette = 12=#00a3e9
# Magenta
palette = 13=#8c8c8c
# Cyan
palette = 14=#a4a4a4
# White
palette = 15=#a4a4a4
