background = #161616
foreground = #dedede

selection-background = #2e2e2e
selection-foreground = #dedede

# Black
palette = 0=#2e2e2e
# Dark Red
palette = 1=#dd7577
# Dark Green
palette = 2=#a9ba78
# Dark Yellow
palette = 3=#d6b174
# Dark Blue
palette = 4=#79b5cc
# Dark Magenta
palette = 5=#8c8c8c
# Dark Cyan
palette = 6=#a4a4a4
# Light Gray
palette = 7=#a4a4a4

# Gray
palette = 8=#5d5d5d
# Red
palette = 9=#dd7577
# Green
palette = 10=#a9ba78
# Yellow
palette = 11=#d6b174
# Blue
palette = 12=#79b5cc
# Magenta
palette = 13=#8c8c8c
# Cyan
palette = 14=#a4a4a4
# White
palette = 15=#a4a4a4
